config/routes.rb
Shop::Application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :products
    resources :categories
    root to: 'categories#index'
  end

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  root to: 'products#index'

  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top"><h1>Super computer shop!</h1></div>
<nav>
  <ul>
    <li>
      <%= link_to 'All products', admin_products_path %>
    </li>
    <% @categories.each do |category| %>
        <li>
          <%= link_to category.name, admin_category_path(category) %>
        </li>
    <% end %>


    <li class="special">
      <%= link_to 'Logout', destroy_admin_session_path, method: :delete %>
    </li>
    <li class="special">
      <%= link_to 'Categories', admin_categories_path %>
    </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top"><h1>Super computer shop!</h1></div>
<nav>
  <ul>
    <li>
      <%= link_to 'Newest products', products_path %>
    </li>
    <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
    </li>
    <% end %>
    <li class="special">
      <%= link_to 'Add category', new_category_path %>
    </li>
    <li class="special">
      <%= link_to 'Add product', new_product_path %>
    </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>